name: discussion-ideas-welcome

on:
  discussion:
    types: [created]

permissions:
  discussions: write

jobs:
  welcome:
    if: ${{ github.event.discussion.category && github.event.discussion.category.slug == 'ideas' }}
    runs-on: ubuntu-latest
    steps:
      - name: Post welcome comment once
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Unique marker to ensure a single comment per discussion
            const marker = '<!-- facc_discussion_ideas_welcome_v1 -->';
            const { owner, repo } = context.repo;
            const discussion_number = context.payload.discussion.number;

            // Fetch existing comments; skip if our marker is present
            const { data: comments } = await github.request(
              'GET /repos/{owner}/{repo}/discussions/{discussion_number}/comments',
              { owner, repo, discussion_number, per_page: 100 }
            );

            if (Array.isArray(comments) && comments.some(c => typeof c.body === 'string' && c.body.includes(marker))) {
              core.info('Welcome comment already exists for this discussion. Skipping.');
              return;
            }

            const body = `${marker}
              This is an automated message from the **Factorio Admin Command Center (FACC)** bot.

              **Category note:** This category is for **new feature ideas** or **improvements to existing features** only. If you want to **report a bug**, please open an **Issue** instead.

              Thanks for starting an **Ideas** discussion! **@louanfontenele** will reply as soon as possible (timezone **GMT-3, Brazil**).

              To help evaluate your idea, please include (or edit the post to add):
              - The problem or use-case your idea solves.
              - The proposed behavior/UX (what should happen, where, when).
              - Where this fits in FACC (admin actions, monitoring, chat, permissions, etc.).
              - Factorio version and FACC version.
              - Context: Singleplayer / Multiplayer (hosted or dedicated).

              **Language policy:** Discussions are welcome in **English** or **Portuguese (pt-BR)**.

              **P.S.:** Just to clarify — this project was created to work **only** with the **Vanilla game and its official DLCs** (such as *Space Age* and its standalone content). While in theory it shouldn’t conflict with others, it was designed and tested to run **without any additional mods installed**. The maintainer will still do their best to consider ideas that involve other mods, but please keep in mind that support is limited to what’s within reach and the scope of the original design.`;

            // Create the comment
            await github.request(
              'POST /repos/{owner}/{repo}/discussions/{discussion_number}/comments',
              { owner, repo, discussion_number, body }
            );
