name: Enforce Current Year in README

# Trigger once a year (Jan 1), on any README.md change, or manually
on:
  schedule:
    - cron: "0 0 1 1 *"
  push:
    paths:
      - README.md
  workflow_dispatch:

jobs:
  enforce-readme-year:
    runs-on: ubuntu-latest

    permissions:
      contents: write # allow commits via GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and update year
        run: |
          current_year=$(date +'%Y')

          # Extract exactly the 4-digit year between the HTML comment markers,
          # even if on the same line.
          extracted=$(grep -oP '(?<=<!--\s*change year start\s*-->)[[:space:]]*[0-9]{4}[[:space:]]*(?=<!--\s*change year end\s*-->)' README.md | tr -d '[:space:]')

          echo "Found year between markers: $extracted"
          echo "Current system year:       $current_year"

          # Only update if it's a valid 4-digit number and differs from today
          if [[ "$extracted" =~ ^[0-9]{4}$ ]] && [[ "$extracted" != "$current_year" ]]; then
            echo "Year differs. Updating to $current_year..."
            
            # In-place replace the old year with the current year
            sed -E -i "s|(<!-- change year start -->)[[:space:]]*[0-9]{4}[[:space:]]*(<!-- change year end -->)|\1 ${current_year} \2|" README.md
            
            echo "YEAR_UPDATED=1" >> $GITHUB_ENV
          else
            echo "No update needed."
            echo "YEAR_UPDATED=0" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.YEAR_UPDATED == '1'
        run: |
          git add README.md
          git commit -m "fix(readme): enforce year ${current_year}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # commits as github-actions[bot]
