name: Enforce Current Year in README

on:
  schedule:
    - cron: "0 0 1 1 *" # Once a year
  push:
    paths:
      - README.md # On any change to README
  workflow_dispatch: # Allow manual trigger

jobs:
  enforce-readme-year:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Necessário para permitir o push com GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and update year
        run: |
          current_year=$(date +'%Y')
          file_year=$(grep -oP '\b20[0-9]{2}\b' README.md | sort -nr | head -n1 || echo "0000")

          echo "Detected year in README: $file_year"
          echo "Current system year: $current_year"

          if [[ "$file_year" =~ ^20[0-9]{2}$ ]] && [[ "$file_year" -lt "$current_year" ]]; then
            echo "Year in README is outdated. Replacing $file_year with $current_year"
            sed -i "s/\b$file_year\b/$current_year/g" README.md
            echo "YEAR_UPDATED=1" >> $GITHUB_ENV
          else
            echo "No update needed."
            echo "YEAR_UPDATED=0" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.YEAR_UPDATED == '1'
        run: |
          git add README.md
          git commit -m "Fix README year to ${current_year}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
