name: Enforce Current Year in README

# Triggered once a year (Jan 1st), on any README change, or manually
on:
  schedule:
    - cron: "0 0 1 1 *"        # Yearly trigger on January 1st
  push:
    paths:
      - README.md             # Any time the README is modified
  workflow_dispatch:         # Allow manual execution from GitHub UI

jobs:
  enforce-readme-year:
    runs-on: ubuntu-latest

    permissions:
      contents: write         # Required for committing changes via GITHUB_TOKEN

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check and update year
        run: |
          current_year=$(date +'%Y')

          # Extract the text between the special HTML comment markers
          extracted=$(awk '/<!-- change year start -->/{flag=1; next} /<!-- change year end -->/{flag=0} flag' README.md | tr -d '[:space:]')

          echo "Found year between markers: $extracted"
          echo "Current system year: $current_year"

          # Validate and compare the extracted year
          if [[ "$extracted" =~ ^20[0-9]{2}$ ]] && [[ "$extracted" -lt "$current_year" ]]; then
            echo "Year is outdated. Updating to $current_year..."

            # Replace the content between the markers
            sed -i "/<!-- change year start -->/,/<!-- change year end -->/c\\<!-- change year start -->\\
$current_year\\
<!-- change year end -->" README.md

            echo "YEAR_UPDATED=1" >> $GITHUB_ENV
          else
            echo "No update needed."
            echo "YEAR_UPDATED=0" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.YEAR_UPDATED == '1'
        run: |
          git add README.md
          git commit -m "fix(readme): update year to ${current_year}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Uses github-actions[bot] for commit
