name: Update README year

on:
  schedule:
    - cron: "0 0 1 1 *" # Runs once a year on January 1st
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace placeholder with current year
        run: |
          year=$(date +'%Y')
          sed -i "s/CURRENT_YEAR/${year}/g" README.md

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@users.noreply.github.com"
          git add README.md
          git commit -m "Update README year to ${year}" || echo "No changes"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:main
