name: Update README year

on:
  schedule:
    - cron: "0 0 1 1 *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repository (without credentials)
        uses: actions/checkout@v3
        with:
          persist-credentials: false # <- isso é crucial

      - name: Replace placeholder with current year
        run: |
          year=$(date +'%Y')
          sed -i "s/CURRENT_YEAR/${year}/g" README.md
          echo "YEAR=$year" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          git config user.name "Auto Bot"
          git config user.email "bot@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add README.md
          git commit -m "Update README year to $YEAR" || echo "No changes"
          git push origin HEAD:main
